/**
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: agpl
 */

// What the toolbar icon is saying, derived from three independent facts.
//
// Pure on purpose: this is the one place that decides what "off" means, and it is
// consulted from the background (to paint the icon), the popup (to label the
// controls) and the content script (to decide whether to look anything up). Three
// copies of that rule would drift within a week.
//
// The three facts are deliberately not collapsed into one traffic light:
//
//   enabled     — the master switch
//   siteEnabled — this host, which the user can turn off without touching the master
//   health      — can the extension reach wudict at all
//
// Icon tint carries *will it act here* (on/off), the badge carries *can it act at
// all* (server reachable), and the tooltip spells out both. A disabled extension on
// a dead server is grey with no badge: the badge would be advice about a problem
// the user has already opted out of.

/** Icon tints. The files are generated by tools/make-icons.mjs. */
export const ICON = { ON: 'on', OFF: 'off' };

export const HEALTH = { OK: 'ok', DOWN: 'down', UNKNOWN: 'unknown' };

/** Hosts are stored bare (no scheme, no port), which is what a user recognises. */
export function hostOf(url) {
  try {
    const parsed = new URL(url);
    if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return null;
    return parsed.hostname || null;
  } catch {
    return null;
  }
}

/**
 * Is the extension allowed to act on this host?
 *
 * Absent means allowed: an opt-out list stays small and survives a settings reset
 * gracefully, where an opt-in list would silently disable the extension everywhere
 * the moment storage is cleared.
 */
export function siteEnabled(settings, host) {
  if (!host) return true;
  return settings?.siteRules?.[host] !== false;
}

/** Both switches. A lookup happens only when this is true. */
export function activeOn(settings, host) {
  return Boolean(settings?.enabled) && siteEnabled(settings, host);
}

/**
 * The full toolbar presentation for one tab.
 *
 * `host` is null when the page is one no content script can run on (a browser
 * settings page, the add-ons manager, a PDF viewer). That is not an error state and
 * must not look like one — the icon simply reports the global switch and says the
 * page is out of scope.
 */
export function toolbarState({ settings, host, health, baseUrl }) {
  const enabled = Boolean(settings?.enabled);
  const site = siteEnabled(settings, host);
  const active = enabled && site;

  const badge = active && health === HEALTH.DOWN ? '!' : '';

  const lines = [];
  if (!enabled) lines.push('Paused everywhere');
  else if (!site) lines.push(`Paused on ${host}`);
  else lines.push('Hover lookup on');

  if (host === null) lines.push('This page cannot be read by the extension');

  if (health === HEALTH.DOWN) lines.push(`Cannot reach wudict at ${baseUrl}`);
  else if (health === HEALTH.OK) lines.push(`Connected to ${baseUrl}`);

  return {
    icon: active ? ICON.ON : ICON.OFF,
    badge,
    // Amber, not red: the extension is fine, the server it talks to is not, and the
    // fix is elsewhere. Red would read as "this extension is broken".
    badgeColour: '#b26a00',
    title: `wudict Hover — ${lines.join(' · ')}`,
    active,
    enabled,
    site,
  };
}
